//Next and Previous buttons
var img = new Array(
  "/VedImages/Sub_1-colormap_1.png",
  "/VedImages/Sub_2-colormap_1.png",
  "/VedImages/Sub_3-colormap_1.png",
  "/VedImages/Sub_4-colormap_1.png",
  "/VedImages/Sub_5-colormap_1.png",
  "/VedImages/Sub_6-colormap_1.png",
  "/VedImages/Sub_7-colormap_1.png",
  "/VedImages/Sub_8-colormap_1.png",
  "/VedImages/Sub_9-colormap_1.png",
  "/VedImages/Sub_10-colormap_1.png",
  "/VedImages/Sub_11-colormap_1.png",
  "/VedImages/Sub_12-colormap_1.png",
  "/VedImages/Sub_13-colormap_1.png",
  "/VedImages/Sub_14-colormap_1.png",
  "/VedImages/Sub_15-colormap_1.png",
  "/VedImages/Sub_16-colormap_1.png",
  "/VedImages/Sub_17-colormap_1.png",
  "/VedImages/Sub_18-colormap_1.png",
  "/VedImages/Sub_19-colormap_1.png",
  "/VedImages/Sub_20-colormap_1.png",
  "/VedImages/Sub_21-colormap_1.png",
  "/VedImages/Sub_22-colormap_1.png",
  "/VedImages/Sub_23-colormap_1.png",
  "/VedImages/Sub_24-colormap_1.png",
  "/VedImages/Sub_25-colormap_1.png",
  "/VedImages/Sub_26-colormap_1.png",
  "/VedImages/Sub_27-colormap_1.png",
  "/VedImages/Sub_28-colormap_1.png",
  "/VedImages/Sub_29-colormap_1.png",
  "/VedImages/Sub_30-colormap_1.png",
  "/VedImages/Sub_31-colormap_1.png",
  "/VedImages/Sub_32-colormap_1.png",
  "/VedImages/Sub_33-colormap_1.png",
  "/VedImages/Sub_34-colormap_1.png",
  "/VedImages/Sub_35-colormap_1.png",
  "/VedImages/Sub_36-colormap_1.png",
  "/VedImages/Sub_37-colormap_1.png",
  "/VedImages/Sub_38-colormap_1.png",
  "/VedImages/Sub_39-colormap_1.png",
  "/VedImages/Sub_40-colormap_1.png",
  "/VedImages/Sub_41-colormap_1.png",
  "/VedImages/Sub_42-colormap_1.png",
  "/VedImages/Sub_43-colormap_1.png",
  "/VedImages/Sub_44-colormap_1.png",
  "/VedImages/Sub_45-colormap_1.png",
  "/VedImages/Sub_46-colormap_1.png",
  "/VedImages/Sub_47-colormap_1.png",
  "/VedImages/Sub_48-colormap_1.png",
  "/VedImages/Sub_49-colormap_1.png",
  "/VedImages/Sub_50-colormap_1.png",
  "/VedImages/Sub_51-colormap_1.png",
  "/VedImages/Sub_52-colormap_1.png",
  "/VedImages/Sub_53-colormap_1.png",
  "/VedImages/Sub_54-colormap_1.png",
  "/VedImages/Sub_55-colormap_1.png",
  "/VedImages/Sub_56-colormap_1.png",
  "/VedImages/Sub_57-colormap_1.png",
  "/VedImages/Sub_58-colormap_1.png",
  "/VedImages/Sub_59-colormap_1.png",
  "/VedImages/Sub_60-colormap_1.png",
  "/VedImages/Sub_61-colormap_1.png",
  "/VedImages/Sub_62-colormap_1.png",
  "/VedImages/Sub_63-colormap_1.png",
  "/VedImages/Sub_64-colormap_1.png",
  "/VedImages/Sub_65-colormap_1.png",
  "/VedImages/Sub_66-colormap_1.png",
  "/VedImages/Sub_67-colormap_1.png",
  "/VedImages/Sub_68-colormap_1.png",
  "/VedImages/Sub_69-colormap_1.png",
  "/VedImages/Sub_70-colormap_1.png",
  "/VedImages/Sub_71-colormap_1.png",
  "/VedImages/Sub_72-colormap_1.png",
  "/VedImages/Sub_73-colormap_1.png",
  "/VedImages/Sub_74-colormap_1.png",
  "/VedImages/Sub_75-colormap_1.png",
  "/VedImages/Sub_76-colormap_1.png",
  "/VedImages/Sub_77-colormap_1.png",
  "/VedImages/Sub_78-colormap_1.png",
  "/VedImages/Sub_79-colormap_1.png",
  "/VedImages/Sub_80-colormap_1.png",
  "/VedImages/Sub_81-colormap_1.png",
  "/VedImages/Sub_82-colormap_1.png",
  "/VedImages/Sub_83-colormap_1.png",
  "/VedImages/Sub_84-colormap_1.png",
  "/VedImages/Sub_85-colormap_1.png",
  "/VedImages/Sub_86-colormap_1.png",
  "/VedImages/Sub_87-colormap_1.png",
  "/VedImages/Sub_88-colormap_1.png",
  "/VedImages/Sub_89-colormap_1.png",
  "/VedImages/Sub_90-colormap_1.png",
  "/VedImages/Sub_91-colormap_1.png",
  "/VedImages/Sub_92-colormap_1.png",
  "/VedImages/Sub_93-colormap_1.png",
  "/VedImages/Sub_94-colormap_1.png",
  "/VedImages/Sub_95-colormap_1.png",
  "/VedImages/Sub_96-colormap_1.png",
  "/VedImages/Sub_97-colormap_1.png",
  "/VedImages/Sub_98-colormap_1.png",
  "/VedImages/Sub_99-colormap_1.png",
  "/VedImages/Sub_100-colormap_1.png",
  "/VedImages/Sub_101-colormap_1.png"
);

var img2 = new Array(
  "/VedImages/Sub_1-colormap_2.png",
  "/VedImages/Sub_2-colormap_2.png",
  "/VedImages/Sub_3-colormap_2.png",
  "/VedImages/Sub_4-colormap_2.png",
  "/VedImages/Sub_5-colormap_2.png",
  "/VedImages/Sub_6-colormap_2.png",
  "/VedImages/Sub_7-colormap_2.png",
  "/VedImages/Sub_8-colormap_2.png",
  "/VedImages/Sub_9-colormap_2.png",
  "/VedImages/Sub_10-colormap_2.png",
  "/VedImages/Sub_11-colormap_2.png",
  "/VedImages/Sub_12-colormap_2.png",
  "/VedImages/Sub_13-colormap_2.png",
  "/VedImages/Sub_14-colormap_2.png",
  "/VedImages/Sub_15-colormap_2.png",
  "/VedImages/Sub_16-colormap_2.png",
  "/VedImages/Sub_17-colormap_2.png",
  "/VedImages/Sub_18-colormap_2.png",
  "/VedImages/Sub_19-colormap_2.png",
  "/VedImages/Sub_20-colormap_2.png",
  "/VedImages/Sub_21-colormap_2.png",
  "/VedImages/Sub_22-colormap_2.png",
  "/VedImages/Sub_23-colormap_2.png",
  "/VedImages/Sub_24-colormap_2.png",
  "/VedImages/Sub_25-colormap_2.png",
  "/VedImages/Sub_26-colormap_2.png",
  "/VedImages/Sub_27-colormap_2.png",
  "/VedImages/Sub_28-colormap_2.png",
  "/VedImages/Sub_29-colormap_2.png",
  "/VedImages/Sub_30-colormap_2.png",
  "/VedImages/Sub_31-colormap_2.png",
  "/VedImages/Sub_32-colormap_2.png",
  "/VedImages/Sub_33-colormap_2.png",
  "/VedImages/Sub_34-colormap_2.png",
  "/VedImages/Sub_35-colormap_2.png",
  "/VedImages/Sub_36-colormap_2.png",
  "/VedImages/Sub_37-colormap_2.png",
  "/VedImages/Sub_38-colormap_2.png",
  "/VedImages/Sub_39-colormap_2.png",
  "/VedImages/Sub_40-colormap_2.png",
  "/VedImages/Sub_41-colormap_2.png",
  "/VedImages/Sub_42-colormap_2.png",
  "/VedImages/Sub_43-colormap_2.png",
  "/VedImages/Sub_44-colormap_2.png",
  "/VedImages/Sub_45-colormap_2.png",
  "/VedImages/Sub_46-colormap_2.png",
  "/VedImages/Sub_47-colormap_2.png",
  "/VedImages/Sub_48-colormap_2.png",
  "/VedImages/Sub_49-colormap_2.png",
  "/VedImages/Sub_50-colormap_2.png",
  "/VedImages/Sub_51-colormap_2.png",
  "/VedImages/Sub_52-colormap_2.png",
  "/VedImages/Sub_53-colormap_2.png",
  "/VedImages/Sub_54-colormap_2.png",
  "/VedImages/Sub_55-colormap_2.png",
  "/VedImages/Sub_56-colormap_2.png",
  "/VedImages/Sub_57-colormap_2.png",
  "/VedImages/Sub_58-colormap_2.png",
  "/VedImages/Sub_59-colormap_2.png",
  "/VedImages/Sub_60-colormap_2.png",
  "/VedImages/Sub_61-colormap_2.png",
  "/VedImages/Sub_62-colormap_2.png",
  "/VedImages/Sub_63-colormap_2.png",
  "/VedImages/Sub_64-colormap_2.png",
  "/VedImages/Sub_65-colormap_2.png",
  "/VedImages/Sub_66-colormap_2.png",
  "/VedImages/Sub_67-colormap_2.png",
  "/VedImages/Sub_68-colormap_2.png",
  "/VedImages/Sub_69-colormap_2.png",
  "/VedImages/Sub_70-colormap_2.png",
  "/VedImages/Sub_71-colormap_2.png",
  "/VedImages/Sub_72-colormap_2.png",
  "/VedImages/Sub_73-colormap_2.png",
  "/VedImages/Sub_74-colormap_2.png",
  "/VedImages/Sub_75-colormap_2.png",
  "/VedImages/Sub_76-colormap_2.png",
  "/VedImages/Sub_77-colormap_2.png",
  "/VedImages/Sub_78-colormap_2.png",
  "/VedImages/Sub_79-colormap_2.png",
  "/VedImages/Sub_80-colormap_2.png",
  "/VedImages/Sub_81-colormap_2.png",
  "/VedImages/Sub_82-colormap_2.png",
  "/VedImages/Sub_83-colormap_2.png",
  "/VedImages/Sub_84-colormap_2.png",
  "/VedImages/Sub_85-colormap_2.png",
  "/VedImages/Sub_86-colormap_2.png",
  "/VedImages/Sub_87-colormap_2.png",
  "/VedImages/Sub_88-colormap_2.png",
  "/VedImages/Sub_89-colormap_2.png",
  "/VedImages/Sub_90-colormap_2.png",
  "/VedImages/Sub_91-colormap_2.png",
  "/VedImages/Sub_92-colormap_2.png",
  "/VedImages/Sub_93-colormap_2.png",
  "/VedImages/Sub_94-colormap_2.png",
  "/VedImages/Sub_95-colormap_2.png",
  "/VedImages/Sub_96-colormap_2.png",
  "/VedImages/Sub_97-colormap_2.png",
  "/VedImages/Sub_98-colormap_2.png",
  "/VedImages/Sub_99-colormap_2.png",
  "/VedImages/Sub_100-colormap_2.png",
  "/VedImages/Sub_101-colormap_2.png"
);

var img3 = new Array(
  "/VedImages/Sub_1-colormap_3.png",
  "/VedImages/Sub_2-colormap_3.png",
  "/VedImages/Sub_3-colormap_3.png",
  "/VedImages/Sub_4-colormap_3.png",
  "/VedImages/Sub_5-colormap_3.png",
  "/VedImages/Sub_6-colormap_3.png",
  "/VedImages/Sub_7-colormap_3.png",
  "/VedImages/Sub_8-colormap_3.png",
  "/VedImages/Sub_9-colormap_3.png",
  "/VedImages/Sub_10-colormap_3.png",
  "/VedImages/Sub_11-colormap_3.png",
  "/VedImages/Sub_12-colormap_3.png",
  "/VedImages/Sub_13-colormap_3.png",
  "/VedImages/Sub_14-colormap_3.png",
  "/VedImages/Sub_15-colormap_3.png",
  "/VedImages/Sub_16-colormap_3.png",
  "/VedImages/Sub_17-colormap_3.png",
  "/VedImages/Sub_18-colormap_3.png",
  "/VedImages/Sub_19-colormap_3.png",
  "/VedImages/Sub_20-colormap_3.png",
  "/VedImages/Sub_21-colormap_3.png",
  "/VedImages/Sub_22-colormap_3.png",
  "/VedImages/Sub_23-colormap_3.png",
  "/VedImages/Sub_24-colormap_3.png",
  "/VedImages/Sub_25-colormap_3.png",
  "/VedImages/Sub_26-colormap_3.png",
  "/VedImages/Sub_27-colormap_3.png",
  "/VedImages/Sub_28-colormap_3.png",
  "/VedImages/Sub_29-colormap_3.png",
  "/VedImages/Sub_30-colormap_3.png",
  "/VedImages/Sub_31-colormap_3.png",
  "/VedImages/Sub_32-colormap_3.png",
  "/VedImages/Sub_33-colormap_3.png",
  "/VedImages/Sub_34-colormap_3.png",
  "/VedImages/Sub_35-colormap_3.png",
  "/VedImages/Sub_36-colormap_3.png",
  "/VedImages/Sub_37-colormap_3.png",
  "/VedImages/Sub_38-colormap_3.png",
  "/VedImages/Sub_39-colormap_3.png",
  "/VedImages/Sub_40-colormap_3.png",
  "/VedImages/Sub_41-colormap_3.png",
  "/VedImages/Sub_42-colormap_3.png",
  "/VedImages/Sub_43-colormap_3.png",
  "/VedImages/Sub_44-colormap_3.png",
  "/VedImages/Sub_45-colormap_3.png",
  "/VedImages/Sub_46-colormap_3.png",
  "/VedImages/Sub_47-colormap_3.png",
  "/VedImages/Sub_48-colormap_3.png",
  "/VedImages/Sub_49-colormap_3.png",
  "/VedImages/Sub_50-colormap_3.png",
  "/VedImages/Sub_51-colormap_3.png",
  "/VedImages/Sub_52-colormap_3.png",
  "/VedImages/Sub_53-colormap_3.png",
  "/VedImages/Sub_54-colormap_3.png",
  "/VedImages/Sub_55-colormap_3.png",
  "/VedImages/Sub_56-colormap_3.png",
  "/VedImages/Sub_57-colormap_3.png",
  "/VedImages/Sub_58-colormap_3.png",
  "/VedImages/Sub_59-colormap_3.png",
  "/VedImages/Sub_60-colormap_3.png",
  "/VedImages/Sub_61-colormap_3.png",
  "/VedImages/Sub_62-colormap_3.png",
  "/VedImages/Sub_63-colormap_3.png",
  "/VedImages/Sub_64-colormap_3.png",
  "/VedImages/Sub_65-colormap_3.png",
  "/VedImages/Sub_66-colormap_3.png",
  "/VedImages/Sub_67-colormap_3.png",
  "/VedImages/Sub_68-colormap_3.png",
  "/VedImages/Sub_69-colormap_3.png",
  "/VedImages/Sub_70-colormap_3.png",
  "/VedImages/Sub_71-colormap_3.png",
  "/VedImages/Sub_72-colormap_3.png",
  "/VedImages/Sub_73-colormap_3.png",
  "/VedImages/Sub_74-colormap_3.png",
  "/VedImages/Sub_75-colormap_3.png",
  "/VedImages/Sub_76-colormap_3.png",
  "/VedImages/Sub_77-colormap_3.png",
  "/VedImages/Sub_78-colormap_3.png",
  "/VedImages/Sub_79-colormap_3.png",
  "/VedImages/Sub_80-colormap_3.png",
  "/VedImages/Sub_81-colormap_3.png",
  "/VedImages/Sub_82-colormap_3.png",
  "/VedImages/Sub_83-colormap_3.png",
  "/VedImages/Sub_84-colormap_3.png",
  "/VedImages/Sub_85-colormap_3.png",
  "/VedImages/Sub_86-colormap_3.png",
  "/VedImages/Sub_87-colormap_3.png",
  "/VedImages/Sub_88-colormap_3.png",
  "/VedImages/Sub_89-colormap_3.png",
  "/VedImages/Sub_90-colormap_3.png",
  "/VedImages/Sub_91-colormap_3.png",
  "/VedImages/Sub_92-colormap_3.png",
  "/VedImages/Sub_93-colormap_3.png",
  "/VedImages/Sub_94-colormap_3.png",
  "/VedImages/Sub_95-colormap_3.png",
  "/VedImages/Sub_96-colormap_3.png",
  "/VedImages/Sub_97-colormap_3.png",
  "/VedImages/Sub_98-colormap_3.png",
  "/VedImages/Sub_99-colormap_3.png",
  "/VedImages/Sub_100-colormap_3.png",
  "/VedImages/Sub_101-colormap_3.png"
);

var imgElement = document.getElementById("imgDemo");
var i = 0;
var imgLen = img.length;

var no_box = document.querySelector(".image");

function next() {
  if (i < imgLen - 1) {
    i++;
    imgElement.src = img[i];
    document.getElementsByClassName("prev").disabled = false;
  } else {
    document.getElementsByClassName("next").disabled = true;
  }
  return setNo();
}

function prev() {
  if (i > 0) {
    i--;
    imgElement.src = img[i];
    document.getElementsByClassName("next").disabled = false;
  } else {
    document.getElementsByClassName("prev").disabled = true;
  }

  return setNo();
}

function setNo() {
  // Change innerhtml
  // var num = i + 1;

  return (document.getElementById("no").innerHTML = "IMAGE " + (i + 1));
}

function one() {
  imgElement.src = img[i];
}

function two() {
  imgElement.src = img2[i];
}

function three() {
  imgElement.src = img3[i];
}
